# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'channel_settings.ui'
#
# Created: Fri Nov 14 22:32:04 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(710, 500)
        Dialog.setMinimumSize(QtCore.QSize(710, 500))
        Dialog.setMaximumSize(QtCore.QSize(710, 500))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 691, 351))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 30, 311, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.spinTemp = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinTemp.setGeometry(QtCore.QRect(210, 30, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinTemp.setFont(font)
        self.spinTemp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.spinTemp.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.spinTemp.setMinimum(-99)
        self.spinTemp.setMaximum(199)
        self.spinTemp.setProperty("value", 10)
        self.spinTemp.setObjectName("spinTemp")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 191, 111))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.spinStartHour = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinStartHour.setGeometry(QtCore.QRect(40, 40, 51, 22))
        self.spinStartHour.setMaximum(24)
        self.spinStartHour.setProperty("value", 24)
        self.spinStartHour.setObjectName("spinStartHour")
        self.spinEndHour = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinEndHour.setGeometry(QtCore.QRect(110, 40, 51, 22))
        self.spinEndHour.setMaximum(24)
        self.spinEndHour.setProperty("value", 24)
        self.spinEndHour.setObjectName("spinEndHour")
        self.spinStartMin = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinStartMin.setGeometry(QtCore.QRect(40, 70, 51, 22))
        self.spinStartMin.setMaximum(59)
        self.spinStartMin.setObjectName("spinStartMin")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(40, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border-style: none;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-style: none;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border-style: none;")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setObjectName("label_3")
        self.spinEndMin = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinEndMin.setGeometry(QtCore.QRect(110, 70, 51, 22))
        self.spinEndMin.setMaximum(59)
        self.spinEndMin.setObjectName("spinEndMin")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-style: none;")
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(270, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-style: none;")
        self.label_5.setObjectName("label_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(360, 30, 311, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.spinTemp_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinTemp_2.setGeometry(QtCore.QRect(210, 30, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinTemp_2.setFont(font)
        self.spinTemp_2.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.spinTemp_2.setMinimum(-99)
        self.spinTemp_2.setMaximum(199)
        self.spinTemp_2.setProperty("value", 10)
        self.spinTemp_2.setObjectName("spinTemp_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 191, 111))
        self.groupBox_5.setObjectName("groupBox_5")
        self.spinStartHour_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinStartHour_2.setGeometry(QtCore.QRect(40, 40, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinStartHour_2.setFont(font)
        self.spinStartHour_2.setMaximum(24)
        self.spinStartHour_2.setProperty("value", 24)
        self.spinStartHour_2.setObjectName("spinStartHour_2")
        self.spinEndHour_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinEndHour_2.setGeometry(QtCore.QRect(110, 40, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinEndHour_2.setFont(font)
        self.spinEndHour_2.setMaximum(24)
        self.spinEndHour_2.setProperty("value", 24)
        self.spinEndHour_2.setObjectName("spinEndHour_2")
        self.spinStartMin_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinStartMin_2.setGeometry(QtCore.QRect(40, 70, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinStartMin_2.setFont(font)
        self.spinStartMin_2.setMaximum(59)
        self.spinStartMin_2.setObjectName("spinStartMin_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(40, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border-style: none;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(110, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border-style: none;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border-style: none;")
        self.label_8.setTextFormat(QtCore.Qt.PlainText)
        self.label_8.setObjectName("label_8")
        self.spinEndMin_2 = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinEndMin_2.setGeometry(QtCore.QRect(110, 70, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinEndMin_2.setFont(font)
        self.spinEndMin_2.setMaximum(59)
        self.spinEndMin_2.setObjectName("spinEndMin_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 70, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border-style: none;")
        self.label_9.setTextFormat(QtCore.Qt.PlainText)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(270, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border-style: none;")
        self.label_10.setObjectName("label_10")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 190, 311, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.spinTemp_3 = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinTemp_3.setGeometry(QtCore.QRect(210, 30, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinTemp_3.setFont(font)
        self.spinTemp_3.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.spinTemp_3.setMinimum(-99)
        self.spinTemp_3.setMaximum(199)
        self.spinTemp_3.setProperty("value", 10)
        self.spinTemp_3.setObjectName("spinTemp_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 20, 191, 111))
        self.groupBox_7.setObjectName("groupBox_7")
        self.spinStartHour_3 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinStartHour_3.setGeometry(QtCore.QRect(40, 40, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinStartHour_3.setFont(font)
        self.spinStartHour_3.setMaximum(24)
        self.spinStartHour_3.setProperty("value", 24)
        self.spinStartHour_3.setObjectName("spinStartHour_3")
        self.spinEndHour_3 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinEndHour_3.setGeometry(QtCore.QRect(110, 40, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinEndHour_3.setFont(font)
        self.spinEndHour_3.setMaximum(24)
        self.spinEndHour_3.setProperty("value", 24)
        self.spinEndHour_3.setObjectName("spinEndHour_3")
        self.spinStartMin_3 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinStartMin_3.setGeometry(QtCore.QRect(40, 70, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinStartMin_3.setFont(font)
        self.spinStartMin_3.setMaximum(59)
        self.spinStartMin_3.setObjectName("spinStartMin_3")
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(40, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border-style: none;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_7)
        self.label_12.setGeometry(QtCore.QRect(110, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-style: none;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_7)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("border-style: none;")
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.spinEndMin_3 = QtWidgets.QSpinBox(self.groupBox_7)
        self.spinEndMin_3.setGeometry(QtCore.QRect(110, 70, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinEndMin_3.setFont(font)
        self.spinEndMin_3.setMaximum(59)
        self.spinEndMin_3.setObjectName("spinEndMin_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_7)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("border-style: none;")
        self.label_14.setTextFormat(QtCore.Qt.PlainText)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(270, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("border-style: none;")
        self.label_15.setObjectName("label_15")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setGeometry(QtCore.QRect(360, 190, 311, 141))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.spinTemp_4 = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinTemp_4.setGeometry(QtCore.QRect(210, 30, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinTemp_4.setFont(font)
        self.spinTemp_4.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.spinTemp_4.setMinimum(-99)
        self.spinTemp_4.setMaximum(199)
        self.spinTemp_4.setProperty("value", 10)
        self.spinTemp_4.setObjectName("spinTemp_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 20, 191, 111))
        self.groupBox_9.setObjectName("groupBox_9")
        self.spinStartHour_4 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinStartHour_4.setGeometry(QtCore.QRect(40, 40, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinStartHour_4.setFont(font)
        self.spinStartHour_4.setMaximum(24)
        self.spinStartHour_4.setProperty("value", 24)
        self.spinStartHour_4.setObjectName("spinStartHour_4")
        self.spinEndHour_4 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinEndHour_4.setGeometry(QtCore.QRect(110, 40, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinEndHour_4.setFont(font)
        self.spinEndHour_4.setMaximum(24)
        self.spinEndHour_4.setProperty("value", 24)
        self.spinEndHour_4.setObjectName("spinEndHour_4")
        self.spinStartMin_4 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinStartMin_4.setGeometry(QtCore.QRect(40, 70, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinStartMin_4.setFont(font)
        self.spinStartMin_4.setMaximum(59)
        self.spinStartMin_4.setObjectName("spinStartMin_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        self.label_16.setGeometry(QtCore.QRect(40, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border-style: none;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_9)
        self.label_17.setGeometry(QtCore.QRect(110, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border-style: none;")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        self.label_18.setGeometry(QtCore.QRect(10, 40, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border-style: none;")
        self.label_18.setTextFormat(QtCore.Qt.PlainText)
        self.label_18.setObjectName("label_18")
        self.spinEndMin_4 = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinEndMin_4.setGeometry(QtCore.QRect(110, 70, 51, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spinEndMin_4.setFont(font)
        self.spinEndMin_4.setMaximum(59)
        self.spinEndMin_4.setObjectName("spinEndMin_4")
        self.label_19 = QtWidgets.QLabel(self.groupBox_9)
        self.label_19.setGeometry(QtCore.QRect(10, 70, 31, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border-style: none;")
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(270, 30, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border-style: none;")
        self.label_20.setObjectName("label_20")
        self.thermosthatNameLabel = QtWidgets.QLabel(Dialog)
        self.thermosthatNameLabel.setGeometry(QtCore.QRect(10, 10, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.thermosthatNameLabel.setFont(font)
        self.thermosthatNameLabel.setObjectName("thermosthatNameLabel")
        self.lineName = QtWidgets.QLineEdit(Dialog)
        self.lineName.setGeometry(QtCore.QRect(60, 20, 531, 22))
        self.lineName.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineName.setStyleSheet("border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;")
        self.lineName.setReadOnly(False)
        self.lineName.setObjectName("lineName")
        self.groupBox_10 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 410, 151, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet("border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;")
        self.groupBox_10.setObjectName("groupBox_10")
        self.spinHisteresis = QtWidgets.QDoubleSpinBox(self.groupBox_10)
        self.spinHisteresis.setGeometry(QtCore.QRect(30, 30, 62, 22))
        self.spinHisteresis.setReadOnly(False)
        self.spinHisteresis.setDecimals(1)
        self.spinHisteresis.setMaximum(4.5)
        self.spinHisteresis.setSingleStep(0.5)
        self.spinHisteresis.setObjectName("spinHisteresis")
        self.buttonSave = QtWidgets.QPushButton(Dialog)
        self.buttonSave.setGeometry(QtCore.QRect(550, 410, 141, 28))
        self.buttonSave.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonSave.setObjectName("buttonSave")
        self.buttonClose = QtWidgets.QPushButton(Dialog)
        self.buttonClose.setGeometry(QtCore.QRect(550, 450, 141, 28))
        self.buttonClose.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonClose.setObjectName("buttonClose")
        self.groupBox_13 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_13.setGeometry(QtCore.QRect(180, 409, 321, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;")
        self.groupBox_13.setObjectName("groupBox_13")
        self.comboDays = QtWidgets.QComboBox(self.groupBox_13)
        self.comboDays.setGeometry(QtCore.QRect(40, 30, 73, 22))
        self.comboDays.setObjectName("comboDays")
        self.checkEnabled = QtWidgets.QCheckBox(self.groupBox_13)
        self.checkEnabled.setGeometry(QtCore.QRect(160, 30, 111, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkEnabled.setFont(font)
        self.checkEnabled.setStyleSheet("border-style: none;")
        self.checkEnabled.setObjectName("checkEnabled")
        self.buttonSaveName = QtWidgets.QPushButton(Dialog)
        self.buttonSaveName.setGeometry(QtCore.QRect(600, 20, 101, 21))
        self.buttonSaveName.setObjectName("buttonSaveName")

        self.retranslateUi(Dialog)
        self.buttonClose.clicked.connect(Dialog.close)
        self.buttonSave.clicked.connect(Dialog.save)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки на термостат"))
        self.groupBox.setTitle(_translate("Dialog", "Часови зони"))
        self.groupBox_2.setTitle(_translate("Dialog", "Зона 1"))
        self.groupBox_3.setTitle(_translate("Dialog", "Интервал на работа"))
        self.label.setText(_translate("Dialog", "От"))
        self.label_2.setText(_translate("Dialog", "До"))
        self.label_3.setText(_translate("Dialog", "Час"))
        self.label_4.setText(_translate("Dialog", "Мин"))
        self.label_5.setText(_translate("Dialog", "tºC"))
        self.groupBox_4.setTitle(_translate("Dialog", "Зона 2"))
        self.groupBox_5.setTitle(_translate("Dialog", "Интервал на работа"))
        self.label_6.setText(_translate("Dialog", "От"))
        self.label_7.setText(_translate("Dialog", "До"))
        self.label_8.setText(_translate("Dialog", "Час"))
        self.label_9.setText(_translate("Dialog", "Мин"))
        self.label_10.setText(_translate("Dialog", "tºC"))
        self.groupBox_6.setTitle(_translate("Dialog", "Зона 3"))
        self.groupBox_7.setTitle(_translate("Dialog", "Интервал на работа"))
        self.label_11.setText(_translate("Dialog", "От"))
        self.label_12.setText(_translate("Dialog", "До"))
        self.label_13.setText(_translate("Dialog", "Час"))
        self.label_14.setText(_translate("Dialog", "Мин"))
        self.label_15.setText(_translate("Dialog", "tºC"))
        self.groupBox_8.setTitle(_translate("Dialog", "Зона 4"))
        self.groupBox_9.setTitle(_translate("Dialog", "Интервал на работа"))
        self.label_16.setText(_translate("Dialog", "От"))
        self.label_17.setText(_translate("Dialog", "До"))
        self.label_18.setText(_translate("Dialog", "Час"))
        self.label_19.setText(_translate("Dialog", "Мин"))
        self.label_20.setText(_translate("Dialog", "tºC"))
        self.thermosthatNameLabel.setText(_translate("Dialog", "Име"))
        self.groupBox_10.setTitle(_translate("Dialog", "Хистерезис ºC"))
        self.buttonSave.setText(_translate("Dialog", "Запис настройки"))
        self.buttonClose.setText(_translate("Dialog", "Затваряне"))
        self.groupBox_13.setTitle(_translate("Dialog", "Дни от седмицата разрешен/забранен"))
        self.checkEnabled.setText(_translate("Dialog", "Разрешен"))
        self.buttonSaveName.setText(_translate("Dialog", "Запис име"))

