# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_controler.ui'
#
# Created: Tue Nov  4 21:11:09 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(730, 336)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 401, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox.setObjectName("groupBox")
        self.lineName = QtWidgets.QLineEdit(self.groupBox)
        self.lineName.setGeometry(QtCore.QRect(70, 30, 311, 22))
        self.lineName.setObjectName("lineName")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 31, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineIPAddress = QtWidgets.QLineEdit(self.groupBox)
        self.lineIPAddress.setGeometry(QtCore.QRect(70, 70, 101, 22))
        self.lineIPAddress.setObjectName("lineIPAddress")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(200, 70, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.linePort = QtWidgets.QLineEdit(self.groupBox)
        self.linePort.setGeometry(QtCore.QRect(240, 70, 31, 22))
        self.linePort.setObjectName("linePort")
        self.btnSaveNameAddrPort = QtWidgets.QPushButton(self.groupBox)
        self.btnSaveNameAddrPort.setGeometry(QtCore.QRect(290, 110, 93, 28))
        self.btnSaveNameAddrPort.setObjectName("btnSaveNameAddrPort")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 10, 281, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(52, 50, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineNewPassword = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineNewPassword.setGeometry(QtCore.QRect(150, 50, 113, 22))
        self.lineNewPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineNewPassword.setObjectName("lineNewPassword")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineNewPasswordRepeat = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineNewPasswordRepeat.setGeometry(QtCore.QRect(150, 80, 113, 22))
        self.lineNewPasswordRepeat.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineNewPasswordRepeat.setObjectName("lineNewPasswordRepeat")
        self.btnSavePassword = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSavePassword.setGeometry(QtCore.QRect(170, 110, 93, 28))
        self.btnSavePassword.setObjectName("btnSavePassword")
        self.lineCurrentPassword = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineCurrentPassword.setGeometry(QtCore.QRect(150, 20, 113, 22))
        self.lineCurrentPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineCurrentPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineCurrentPassword.setObjectName("lineCurrentPassword")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(40, 20, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 180, 251, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(80, 30, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineLocalIPAddress = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineLocalIPAddress.setGeometry(QtCore.QRect(130, 30, 101, 22))
        self.lineLocalIPAddress.setObjectName("lineLocalIPAddress")
        self.btnSaveLocalIPAddress = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSaveLocalIPAddress.setGeometry(QtCore.QRect(140, 110, 93, 28))
        self.btnSaveLocalIPAddress.setObjectName("btnSaveLocalIPAddress")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineLocalIPAddressRepeat = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineLocalIPAddressRepeat.setGeometry(QtCore.QRect(130, 70, 101, 22))
        self.lineLocalIPAddressRepeat.setObjectName("lineLocalIPAddressRepeat")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 180, 201, 151))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineLocalPort = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineLocalPort.setGeometry(QtCore.QRect(140, 30, 31, 22))
        self.lineLocalPort.setMaxLength(3)
        self.lineLocalPort.setObjectName("lineLocalPort")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(100, 30, 41, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.btnSaveLocalPort = QtWidgets.QPushButton(self.groupBox_4)
        self.btnSaveLocalPort.setGeometry(QtCore.QRect(90, 110, 93, 28))
        self.btnSaveLocalPort.setObjectName("btnSaveLocalPort")
        self.lineLocalPort_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineLocalPort_2.setGeometry(QtCore.QRect(140, 70, 31, 22))
        self.lineLocalPort_2.setObjectName("lineLocalPort_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(40, 70, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setGeometry(QtCore.QRect(620, 290, 93, 28))
        self.btnClose.setObjectName("btnClose")
        self.btnReset = QtWidgets.QPushButton(Dialog)
        self.btnReset.setGeometry(QtCore.QRect(620, 250, 93, 28))
        self.btnReset.setObjectName("btnReset")

        self.retranslateUi(Dialog)
        self.btnClose.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Редакция на контролер"))
        self.groupBox.setTitle(_translate("Dialog", "Промяна на име и адрес/порт"))
        self.label.setText(_translate("Dialog", "Име"))
        self.lineIPAddress.setInputMask(_translate("Dialog", "000.000.000.000;_"))
        self.label_2.setText(_translate("Dialog", "Адрес"))
        self.label_3.setText(_translate("Dialog", "Порт"))
        self.linePort.setInputMask(_translate("Dialog", "000;_"))
        self.btnSaveNameAddrPort.setText(_translate("Dialog", "Запис"))
        self.groupBox_2.setTitle(_translate("Dialog", "Промяна на парола"))
        self.label_4.setText(_translate("Dialog", "Нова парола"))
        self.label_5.setText(_translate("Dialog", "Повторете парола"))
        self.btnSavePassword.setText(_translate("Dialog", "Запис"))
        self.label_10.setText(_translate("Dialog", "Текуща парола"))
        self.groupBox_3.setTitle(_translate("Dialog", "Промяна на локален адрес"))
        self.label_6.setText(_translate("Dialog", "Адрес"))
        self.lineLocalIPAddress.setInputMask(_translate("Dialog", "000.000.000.000;_"))
        self.btnSaveLocalIPAddress.setText(_translate("Dialog", "Запис"))
        self.label_8.setText(_translate("Dialog", "Повторете адрес"))
        self.lineLocalIPAddressRepeat.setInputMask(_translate("Dialog", "000.000.000.000;_"))
        self.groupBox_4.setTitle(_translate("Dialog", "Промяна на локален порт"))
        self.lineLocalPort.setInputMask(_translate("Dialog", "000;_"))
        self.label_7.setText(_translate("Dialog", "Порт"))
        self.btnSaveLocalPort.setText(_translate("Dialog", "Запис"))
        self.lineLocalPort_2.setInputMask(_translate("Dialog", "000;_"))
        self.label_9.setText(_translate("Dialog", "Повторете порт"))
        self.btnClose.setText(_translate("Dialog", "Затваряне"))
        self.btnReset.setText(_translate("Dialog", "Reset"))

