# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'general_thermostat_settings.ui'
#
# Created: Fri Nov 14 22:28:53 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeneralSettingsDialog(object):
    def setupUi(self, GeneralSettingsDialog):
        GeneralSettingsDialog.setObjectName("GeneralSettingsDialog")
        GeneralSettingsDialog.resize(650, 520)
        GeneralSettingsDialog.setMinimumSize(QtCore.QSize(650, 520))
        GeneralSettingsDialog.setMaximumSize(QtCore.QSize(650, 520))
        GeneralSettingsDialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.groupBox = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 220, 221, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 30, 181, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.btnSaveDateTime = QtWidgets.QPushButton(self.groupBox)
        self.btnSaveDateTime.setGeometry(QtCore.QRect(140, 70, 73, 28))
        self.btnSaveDateTime.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.btnSaveDateTime.setObjectName("btnSaveDateTime")
        self.groupBox_2 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 220, 171, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioCool = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioCool.setGeometry(QtCore.QRect(30, 20, 111, 20))
        self.radioCool.setStyleSheet("border-style: none;")
        self.radioCool.setChecked(True)
        self.radioCool.setObjectName("radioCool")
        self.radioHeat = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioHeat.setGeometry(QtCore.QRect(30, 40, 101, 20))
        self.radioHeat.setStyleSheet("border-style: none;")
        self.radioHeat.setObjectName("radioHeat")
        self.btnSaveMode = QtWidgets.QPushButton(self.groupBox_2)
        self.btnSaveMode.setGeometry(QtCore.QRect(90, 70, 73, 28))
        self.btnSaveMode.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnSaveMode.setObjectName("btnSaveMode")
        self.groupBox_3 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox_3.setGeometry(QtCore.QRect(440, 220, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.spinTmin = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinTmin.setGeometry(QtCore.QRect(30, 30, 51, 22))
        self.spinTmin.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.spinTmin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinTmin.setMinimum(-99)
        self.spinTmin.setMaximum(199)
        self.spinTmin.setObjectName("spinTmin")
        self.btnSaveTminTmax = QtWidgets.QPushButton(self.groupBox_3)
        self.btnSaveTminTmax.setGeometry(QtCore.QRect(120, 70, 73, 28))
        self.btnSaveTminTmax.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnSaveTminTmax.setObjectName("btnSaveTminTmax")
        self.spinTmax = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinTmax.setGeometry(QtCore.QRect(120, 30, 51, 22))
        self.spinTmax.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinTmax.setMinimum(-99)
        self.spinTmax.setMaximum(199)
        self.spinTmax.setObjectName("spinTmax")
        self.groupInOutMap = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupInOutMap.setGeometry(QtCore.QRect(10, 10, 631, 191))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupInOutMap.setFont(font)
        self.groupInOutMap.setStyleSheet("QGroupBox { border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px; }")
        self.groupInOutMap.setObjectName("groupInOutMap")
        self.btnSaveRouting = QtWidgets.QPushButton(self.groupInOutMap)
        self.btnSaveRouting.setGeometry(QtCore.QRect(550, 150, 73, 28))
        self.btnSaveRouting.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnSaveRouting.setObjectName("btnSaveRouting")
        self.btnClose = QtWidgets.QPushButton(GeneralSettingsDialog)
        self.btnClose.setGeometry(QtCore.QRect(280, 480, 93, 28))
        self.btnClose.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnClose.setObjectName("btnClose")
        self.groupBox_5 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 350, 221, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioOn = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioOn.setGeometry(QtCore.QRect(30, 20, 95, 20))
        self.radioOn.setStyleSheet("border-style: none;")
        self.radioOn.setChecked(True)
        self.radioOn.setObjectName("radioOn")
        self.radioOff = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioOff.setGeometry(QtCore.QRect(30, 40, 95, 20))
        self.radioOff.setStyleSheet("border-style: none;")
        self.radioOff.setObjectName("radioOff")
        self.btnSaveOnOff = QtWidgets.QPushButton(self.groupBox_5)
        self.btnSaveOnOff.setGeometry(QtCore.QRect(140, 70, 73, 28))
        self.btnSaveOnOff.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnSaveOnOff.setObjectName("btnSaveOnOff")
        self.groupBox_6 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox_6.setGeometry(QtCore.QRect(250, 349, 171, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.spinLogInterval = QtWidgets.QSpinBox(self.groupBox_6)
        self.spinLogInterval.setGeometry(QtCore.QRect(30, 30, 81, 22))
        self.spinLogInterval.setMinimum(1)
        self.spinLogInterval.setMaximum(9999)
        self.spinLogInterval.setProperty("value", 5)
        self.spinLogInterval.setObjectName("spinLogInterval")
        self.btnSaveLogInterval = QtWidgets.QPushButton(self.groupBox_6)
        self.btnSaveLogInterval.setGeometry(QtCore.QRect(90, 70, 73, 28))
        self.btnSaveLogInterval.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnSaveLogInterval.setObjectName("btnSaveLogInterval")
        self.groupBox_4 = QtWidgets.QGroupBox(GeneralSettingsDialog)
        self.groupBox_4.setGeometry(QtCore.QRect(440, 350, 201, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {border-color: rgb(0, 0, 0);border-style: solid; border-width: 1px;}")
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioDatalogOn = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioDatalogOn.setGeometry(QtCore.QRect(30, 20, 82, 17))
        self.radioDatalogOn.setChecked(True)
        self.radioDatalogOn.setObjectName("radioDatalogOn")
        self.radioDatalogOff = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioDatalogOff.setGeometry(QtCore.QRect(30, 40, 82, 17))
        self.radioDatalogOff.setObjectName("radioDatalogOff")
        self.btnSaveDatalogOnOff = QtWidgets.QPushButton(self.groupBox_4)
        self.btnSaveDatalogOnOff.setGeometry(QtCore.QRect(120, 70, 73, 28))
        self.btnSaveDatalogOnOff.setFocusPolicy(QtCore.Qt.TabFocus)
        self.btnSaveDatalogOnOff.setObjectName("btnSaveDatalogOnOff")

        self.retranslateUi(GeneralSettingsDialog)
        self.btnClose.clicked.connect(GeneralSettingsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(GeneralSettingsDialog)

    def retranslateUi(self, GeneralSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        GeneralSettingsDialog.setWindowTitle(_translate("GeneralSettingsDialog", "Общи настройки на Мултитермостат 1"))
        self.groupBox.setTitle(_translate("GeneralSettingsDialog", "Дата и час"))
        self.btnSaveDateTime.setText(_translate("GeneralSettingsDialog", "Запис"))
        self.groupBox_2.setTitle(_translate("GeneralSettingsDialog", "Режим"))
        self.radioCool.setText(_translate("GeneralSettingsDialog", "Охлаждане"))
        self.radioHeat.setText(_translate("GeneralSettingsDialog", "Отопление"))
        self.btnSaveMode.setText(_translate("GeneralSettingsDialog", "Запис"))
        self.groupBox_3.setTitle(_translate("GeneralSettingsDialog", "T Min и T Max ºC"))
        self.btnSaveTminTmax.setText(_translate("GeneralSettingsDialog", "Запис"))
        self.groupInOutMap.setTitle(_translate("GeneralSettingsDialog", "Мапинг на входовете към изходните канали "))
        self.btnSaveRouting.setText(_translate("GeneralSettingsDialog", "Запис"))
        self.btnClose.setText(_translate("GeneralSettingsDialog", "Затваряне"))
        self.groupBox_5.setTitle(_translate("GeneralSettingsDialog", "Включен / Изключен"))
        self.radioOn.setText(_translate("GeneralSettingsDialog", "Включен"))
        self.radioOff.setText(_translate("GeneralSettingsDialog", "Изключен"))
        self.btnSaveOnOff.setText(_translate("GeneralSettingsDialog", "Запис"))
        self.groupBox_6.setTitle(_translate("GeneralSettingsDialog", "Лог интервал мин"))
        self.btnSaveLogInterval.setText(_translate("GeneralSettingsDialog", "Запис"))
        self.groupBox_4.setTitle(_translate("GeneralSettingsDialog", "Дата лог Включен/Изключен"))
        self.radioDatalogOn.setText(_translate("GeneralSettingsDialog", "Включен"))
        self.radioDatalogOff.setText(_translate("GeneralSettingsDialog", "Изключен"))
        self.btnSaveDatalogOnOff.setText(_translate("GeneralSettingsDialog", "Запис"))

